In [16]:
import pandas as pd
import sqlite3

In [17]:
orders = pd.read_csv("orders.csv")
orders.head()

,order_id,user_id,restaurant_id,order_date,total_amount,restaurant_name
0,1,2508,450,18-02-2023,842.97,New Foods Chinese
1,2,2693,309,18-01-2023,546.68,Ruchi Curry House Multicuisine
2,3,2084,107,15-07-2023,163.93,Spice Kitchen Punjabi
3,4,319,224,04-10-2023,1155.97,Darbar Kitchen Non-Veg
4,5,1064,293,25-12-2023,1321.91,Royal Eatery South Indian

In [18]:
users = pd.read_json("users.json")
users.head()

   user_id    name       city membership
0        1  User_1    Chennai    Regular
1        2  User_2       Pune       Gold
2        3  User_3  Bangalore       Gold
3        4  User_4  Bangalore    Regular
4        5  User_5       Pune       Gold

In [19]:
conn = sqlite3.connect(":memory:")

In [20]:
users = pd.read_json("users.json")
users.head()

   user_id    name       city membership
0        1  User_1    Chennai    Regular
1        2  User_2       Pune       Gold
2        3  User_3  Bangalore       Gold
3        4  User_4  Bangalore    Regular
4        5  User_5       Pune       Gold

In [21]:
conn = sqlite3.connect(":memory:")

In [22]:
with open("restaurants.sql", "r", encoding="utf-8") as f:
    sql_script = f.read()

conn.executescript(sql_script)

In [23]:
restaurants = pd.read_sql(
    "SELECT * FROM restaurants",
    conn
)

restaurants.head()

   restaurant_id restaurant_name  cuisine  rating
0              1    Restaurant_1  Chinese     4.8
1              2    Restaurant_2   Indian     4.1
2              3    Restaurant_3  Mexican     4.3
3              4    Restaurant_4  Chinese     4.1
4              5    Restaurant_5  Chinese     4.8

In [24]:
orders_users = orders.merge(
    users,
    on="user_id",
    how="left"
)

In [25]:
final_df = orders_users.merge(
    restaurants,
    on="restaurant_id",
    how="left"
)

In [26]:
final_df.head()

,order_id,user_id,restaurant_id,order_date,total_amount,restaurant_name_x,name,city,membership,restaurant_name_y,cuisine,rating
0,1,2508,450,18-02-2023,842.97,New Foods Chinese,User_2508,Hyderabad,Regular,Restaurant_450,Mexican,3.2
1,2,2693,309,18-01-2023,546.68,Ruchi Curry House Multicuisine,User_2693,Pune,Regular,Restaurant_309,Indian,4.5
2,3,2084,107,15-07-2023,163.93,Spice Kitchen Punjabi,User_2084,Chennai,Gold,Restaurant_107,Mexican,4.0
3,4,319,224,04-10-2023,1155.97,Darbar Kitchen Non-Veg,User_319,Bangalore,Gold,Restaurant_224,Chinese,4.8
4,5,1064,293,25-12-2023,1321.91,Royal Eatery South Indian,User_1064,Pune,Regular,Restaurant_293,Italian,3.0

In [27]:
final_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   order_id           10000 non-null  int64
 1   user_id            10000 non-null  int64
 2   restaurant_id      10000 non-null  int64
 3   order_date         10000 non-null  str
 4   total_amount       10000 non-null  float64
 5   restaurant_name_x  10000 non-null  str
 6   name               10000 non-null  str
 7   city               10000 non-null  str
 8   membership         10000 non-null  str
 9   restaurant_name_y  10000 non-null  str
 10  cuisine            10000 non-null  str
 11  rating             10000 non-null  float64
dtypes: float64(2), int64(3), str(7)
memory usage: 937.6 KB

In [28]:
final_df.to_csv(
    "final_food_delivery_dataset.csv",
    index=False
)

In [29]:
import os
os.listdir()

['analysis.ipynb',
 'final_food_delivery_dataset.csv',
 'orders.csv',
 'restaurants.sql',
 'users.json']